const Action = {
	CHANGE_COMPONENT: {
		TYPE: "CHANGE_COMPONENT",
		PAYLOAD: {
			FUN: {
				RENAME: "CHANGE_COMPONENT__ANIME_RENAME",
				FUEL_WORKER: "CHANGE_COMPONENT__FUEL_WORKER",
				STOP_APPS : "CHANGE_COMPONENT__STOP_APPS",
				SYSTEM_MONITOR : "CHANGE_COMPONENT__SYSTEM_MONITOR"
			},
			DEV: {
				START_SERVERS: "CHANGE_COMPONENT__WEB_START_SERVER"
			},
			NONE: "CHANGE_COMPONENT__NONE"
		}
	},
	
	SYSTEM_MONITOR : {
		CHANGE_SPEED : {
			TYPE : "SYSTEM_MONITOR__CHANGE_SPEED",
			PAYLOAD : {
				MIN : Infinity,
				LOWER : 4,
				LOW : 2,
				NORMAL : 1,
				HIGH : 0.5,
				HIGHEST: 0.25,
				MAX : 0.2,
			}
		},
		
	
	},

	FUEL_FINDER : {
		CHANGE_FUEL : {TYPE : "FUEL_FINDER__CHANGE_FUEL"},
		CHANGE_FORMAT : {TYPE: "FUEL_FINDER__CHANGE_FORMAT"},
		CHANGE_CP : {TYPE: "FUEL_FINDER__CHANGE_CP"},
		REORDER : {TYPE : "FUEL_FINDER__REORDER"},
		CHANGE_SORTER : {TYPE : "FUEL_FINDER__CHANGE_SORTER"}


	}
};


export {
	Action
}
